env:
  node: true
  browser: true
  es6: true
  mocha: true
extends: 'eslint:recommended'
rules:
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
